### ISSUE TITLE
Arabic text doesn't appear

### ISSUE THREAD

**Issue by 91ns** [UniversalDependencies/UD_Arabic-NYUAD#1]
Hello, 
I downloaded this Dataset and it looks like Arabic text isn't appearing properly. Is there another source where I can download the original data from?

This is what it looks like: 
# sent_id = 20000715_AFP_ARB.0001:1
# text = _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
1	_	_	PROPN	NOUN_PROP	Definite=Ind|Gender=Masc|Number=Sing	0	root	_	_
2	_	_	PROPN	NOUN_PROP	Definite=Ind|Gender=Masc|Number=Sing	1	flat:name	_	_
3	_	_	PUNCT	PUNC	_	4	punct	_	_
4	_	_	NOUN	DET+NOUN+NSUFF_FEM_PL+CASE_DEF_NOM	Case=Nom|Definite=Def|Gender=Fem|Number=Plur	1	nmod	_	_
5	_	_	ADJ	DET+ADJ+NSUFF_FEM_SG+CASE_DEF_NOM	Case=Nom|Definite=Def|Gender=Fem|Number=Sing	4	amod	_	_
6	_	_	PUNCT	PUNC	_	4	punct	_	_
7	_	_	NUM	NOUN_NUM	NumForm=Digit	1	nummod	_	_
8	_	_	PUNCT	PUNC	_	9	punct	_	_
9	_	_	PROPN	ABBREV	_	1	nmod	_	_
10	_	_	PROPN	ABBREV	_	9	flat:name	_	_
11	_	_	PUNCT	PUNC	_	9	punct	_	_
12	_	_	PUNCT	PUNC	_	1	punct	_	_
13	_	_	NOUN	NOUN_QUANT+CASE_DEF_NOM	Case=Nom|Definite=Com|Gender=Masc|Number=Sing	15	nsubj	_	_
14	_	_	NOUN	NOUN+CASE_INDEF_GEN	Case=Gen|Definite=Ind|Gender=Masc|Number=Sing	13	nmod:poss	_	_
15	_	_	VERB	PV+PVSUFF_SUBJ:3MS	Aspect=Perf|Gender=Masc|Mood=Ind|Number=Sing|Person=3|Voice=Act	1	parataxis	_	_
16	_	_	ADP	PREP	AdpType=Prep	17	case	_	_
17	_	_	NOUN	NOUN+NSUFF_FEM_SG+CASE_DEF_GEN	Case=Gen|Definite=Com|Gender=Fem|Number=Sing	15	nmod	_	_
18	_	_	NOUN	DET+ADJ+CASE_DEF_GEN	Case=Gen|Definite=Def|Gender=Masc|Number=Sing	17	nmod:poss	_	_
19	_	_	PROPN	NOUN_PROP	Definite=Ind|Gender=Masc|Number=Sing	18	appos	_	_
20	_	_	PROPN	NOUN_PROP	Definite=Ind|Gender=Masc|Number=Sing	19	flat:name	_	_
21-22	_	_	_	_	_	_	_	_	_
21	_	_	NOUN	NOUN+CASE_DEF_ACC	Case=Acc|Definite=Com|Gender=Masc|Number=Sing	15	nmod	_	_
22	_	mA	SCONJ	SUB_CONJ	_	23	mark	_	_
23	_	_	VERB	PV+PVSUFF_SUBJ:3FS	Aspect=Perf|Gender=Fem|Mood=Ind|Number=Sing|Person=3|Voice=Act	21	ccomp	_	_
24-25	_	_	_	_	_	_	_	_	_
24	_	_	ADP	PREP	AdpType=Prep	25	case	_	_
25	_	h	PRON	PRON_3MS	Definite=Def|Gender=Masc|Number=Sing|Person=3|PronType=Prs	23	nmod	_	_
26-27	_	_	_	_	_	_	_	_	_
26	_	_	NOUN	NOUN+NSUFF_FEM_SG+CASE_DEF_NOM	Case=Nom|Definite=Com|Gender=Fem|Number=Sing	23	nsubj	_	_
27	_	h	PRON	POSS_PRON_3MS	Case=Gen|Definite=Def|Gender=Masc|Number=Sing|Person=3|PronType=Prs	26	nmod:poss	_	_
28	_	_	ADV	NOUN+CASE_DEF_ACC	Case=Acc|Definite=Com|Gender=Masc|Number=Sing	23	advmod	_	_
29	_	_	NOUN	NOUN+CASE_INDEF_GEN	Case=Gen|Definite=Ind|Gender=Masc|Number=Sing	28	nmod:poss	_	_
30	_	_	ADJ	ADJ+CASE_INDEF_GEN	Case=Gen|Definite=Ind|Gender=Masc|Number=Sing	29	amod	_	_
31-33	_	_	_	_	_	_	_	_	_
31	_	l	ADP	PREP	AdpType=Prep	32	case	_	_
32	_	_	VERB	IV3FS+IV+IVSUFF_MOOD:S	Aspect=Imp|Gender=Fem|Mood=Sub|Number=Sing|Person=3|Voice=Act	23	xcomp	_	_
33	_	h	PRON	IVSUFF_DO:3MS	Case=Acc|Definite=Def|Gender=Masc|Number=Sing|Person=3|PronType=Prs	32	obj	_	_
34-36	_	_	_	_	_	_	_	_	_
34	_	b	ADP	PREP	AdpType=Prep	36	case	_	_
35	_	_	SCONJ	SUB_CONJ	_	36	mark	_	_
36	_	h	PRON	PRON_3MS	Definite=Def|Gender=Masc|Number=Sing|Person=3|PronType=Prs	32	nmod	_	_
37	_	_	VERB	PV+PVSUFF_SUBJ:3MS	Aspect=Perf|Gender=Masc|Mood=Ind|Number=Sing|Person=3|Voice=Act	36	ccomp	_	_
38	_	_	NUM	NOUN_NUM	NumForm=Digit	39	obj	_	_
39	_	_	NUM	NOUN_NUM+CASE_DEF_ACC	Case=Acc|Definite=Com|Gender=Masc|Number=Sing|NumForm=Word	40	nummod	_	_
40	_	_	NOUN	NOUN+CASE_INDEF_GEN	Case=Gen|Definite=Ind|Gender=Masc|Number=Sing	37	obj	_	_
41-44	_	_	_	_	_	_	_	_	_
41	_	w	CCONJ	CONJ	_	36	cc	_	_
42	_	b	ADP	PREP	AdpType=Prep	44	case	_	_
43	_	_	SCONJ	SUB_CONJ	_	44	mark	_	_
44	_	h	PRON	PRON_3MS	Definite=Def|Gender=Masc|Number=Sing|Person=3|PronType=Prs	36	conj	_	_
45	_	_	VERB	PV+PVSUFF_SUBJ:3MS	Aspect=Perf|Gender=Masc|Mood=Ind|Number=Sing|Person=3|Voice=Act	44	ccomp	_	_
46	_	_	ADJ	ADJ+CASE_INDEF_ACC	Case=Acc|Definite=Ind|Gender=Masc|Number=Sing	1	parataxis	_	_
47	_	_	ADP	PREP	AdpType=Prep	48	case	_	_
48	_	_	NOUN	NOUN+CASE_DEF_GEN	Case=Gen|Definite=Com|Gender=Masc|Number=Sing	46	nmod	_	_
49	_	_	NOUN	NOUN+CASE_INDEF_GEN	Case=Gen|Definite=Ind|Gender=Masc|Number=Sing	48	nmod:poss	_	_
50-51	_	_	_	_	_	_	_	_	_
50	_	l	ADP	PREP	AdpType=Prep	52	case	_	_
51	_	_	NUM	NOUN_NUM+NSUFF_MASC_PL_GEN	Case=Gen|Definite=Ind|Gender=Masc|Number=Plur|NumForm=Word	52	nummod	_	_
52	_	_	NOUN	NOUN+NSUFF_FEM_SG+CASE_INDEF_ACC	Case=Acc|Definite=Ind|Gender=Fem|Number=Sing	48	nmod	_	_
53	_	_	ADP	PREP	AdpType=Prep	54	case	_	_
54	_	_	NOUN	NOUN+NSUFF_FEM_SG+CASE_DEF_GEN	Case=Gen|Definite=Com|Gender=Fem|Number=Sing	52	nmod	_	_
55	_	_	NOUN	DET+NOUN+CASE_DEF_GEN	Case=Gen|Definite=Def|Gender=Masc|Number=Sing	54	nmod:poss	_	_
56	_	_	ADP	PREP	AdpType=Prep	57	case	_	_
57	_	_	NOUN	NOUN+CASE_DEF_GEN	Case=Gen|Definite=Com|Gender=Masc|Number=Sing	55	nmod	_	_
58	_	_	NOUN	NOUN+NSUFF_FEM_SG+CASE_DEF_GEN	Case=Gen|Definite=Com|Gender=Fem|Number=Sing	57	nmod:poss	_	_
59	_	_	PROPN	NOUN_PROP	Definite=Ind|Gender=Masc|Number=Sing	58	nmod:poss	_	_
60	_	_	PROPN	NOUN_PROP	Definite=Ind|Gender=Masc|Number=Sing	59	flat:name	_	_
61	_	_	ADP	PREP	AdpType=Prep	62	case	_	_
62	_	_	NOUN	NOUN+NSUFF_FEM_SG+CASE_DEF_GEN	Case=Gen|Definite=Com|Gender=Fem|Number=Sing	58	nmod	_	_
63	_	_	PROPN	NOUN_PROP	Definite=Ind|Gender=Masc|Number=Sing	62	nmod:poss	_	_
64	_	_	PUNCT	PUNC	_	15	punct	_	_

**Comment by odanoburu** [comment]
to obtain the full data, follow these steps: https://github.com/UniversalDependencies/UD_Arabic-NYUAD/blob/master/README.md#data
